services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - ./data:/data/db
        network_mode: host
    mediamtx:
        image: bluenviron/mediamtx
        volumes:
            - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
            - ./server.key:/server.key:ro
            - ./server.crt:/server.crt:ro
        network_mode: host
    flask-video-app:
        depends_on:
            - mongo
        environment:
            MTX_API_HOST: ${MTX_API_HOST}
            MTX_API_HOST_PORT: ${MTX_API_HOST_PORT}
            MTX_LIVE_HOST: ${MTX_LIVE_HOST}
            MTX_LIVE_HOST_PORT: ${MTX_LIVE_HOST_PORT}
            MONGO_HOST: ${MONGO_HOST}
            MONGO_PORT: ${MONGO_PORT}
            SECRET_KEY: ${SECRET_KEY}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            MONGO_DB_NAME: ${MONGO_DB_NAME}
        build: .
        command: ./boot.sh
        network_mode: host
    nginx:
        image: nginx:alpine
        depends_on:
            - flask-video-app
            - mediamtx
        volumes:
            - ./app/static:/www/static
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./server.key:/server.key:ro
            - ./server.crt:/server.crt:ro
        network_mode: host