services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=data_server'
            - 'POSTGRES_PASSWORD=data_87468757'
            - 'POSTGRES_USER=admin'
        network_mode: host
    mediamtx:
        image: bluenviron/mediamtx
        volumes:
            - "./mediamtx.yml:/mediamtx.yml:ro"
            - "./server.key:/server.key:ro"
            - "./server.crt:/server.crt:ro"
        network_mode: host
    flask-video-app:
        depends_on:
            - postgres
        environment:
          API_HOST: ${API_HOST}
          LIVE_HOST: ${LIVE_HOST}
        build: .
        command: ./boot.sh
        network_mode: host
    nginx:
        image: nginx:alpine
        depends_on:
            - flask-video-app
            - mediamtx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./server.key:/server.key:ro
            - ./server.crt:/server.crt:ro
        network_mode: host