services:
    web-app:
        environment:
            env_file: .env
        build: .
        command: ./boot.sh
        ports:
            - "5000:5000"
    nginx:
        image: nginx:alpine
        ports:
            - "8088:8088"
        depends_on:
            - web-app
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf