services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: video_service
            MONGO_INITDB_ROOT_PASSWORD: video_134887
        network_mode: host
    mediamtx:
        image: bluenviron/mediamtx
        volumes:
            - "./mediamtx.yml:/mediamtx.yml:ro"
            - "./server.key:/server.key:ro"
            - "./server.crt:/server.crt:ro"
        network_mode: host
    flask-video-app:
        depends_on:
            - mongo
        environment:
          API_HOST: ${API_HOST}
          LIVE_HOST: ${LIVE_HOST}
        build: .
        command: ./boot.sh
        network_mode: host
    nginx:
        image: nginx:alpine
        depends_on:
            - flask-video-app
            - mediamtx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./server.key:/server.key:ro
            - ./server.crt:/server.crt:ro
        network_mode: host