services:
    mediamtx:
        image: bluenviron/mediamtx
        volumes:
            - "./mediamtx.yml:/mediamtx.yml:ro"
            - "./server.key:/server.key:ro"
            - "./server.crt:/server.crt:ro"
        network_mode: host
    flask-video-app:
        environment:
          API_HOST: ${API_HOST}
          LIVE_HOST: ${LIVE_HOST}
        build: .
        command: ./boot.sh
        ports:
            - "5000:5000"
    nginx:
        image: nginx:alpine
        ports:
            - "8088:8088"
        depends_on:
            - flask-video-app
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf