services:
    web-app:
        environment:
            env_file: .env
        build: .
        command: ./boot.sh
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        depends_on:
            - web-app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf